#pragma once
#include <xme/core/concepts/same_as.hpp>
#include <xme/core/concepts/derived_from.hpp>
#include <xme/core/concepts/convertible.hpp>
#include <xme/core/concepts/common.hpp>
#include <xme/core/concepts/arithmetic.hpp>
#include <xme/core/concepts/assignable.hpp>
#include <xme/core/concepts/swappable.hpp>
#include <xme/core/concepts/destructible.hpp>
#include <xme/core/concepts/constructible.hpp>
